### PR TITLE
Add simple support for horizontal lists

### PR DESCRIPTION
**Pull request by dmytro-lytvyn**
This adds a support for "horizontal" lists (requested in https://github.com/fivecar/react-native-draglist/issues/29) like this:
```
<DragList
  horizontal={true}
  data={data}
  keyExtractor={keyExtractor}
  renderItem={renderItem}
  onReordered={onReordered}
/>
```
I know that the implementation is not elegant in the slightest, but I'm not a TypeScript or React developer and I just wanted to make it work _somehow_, which it does.

If someone can make the implementation more generic, it would be great.

The change with `function DragListImpl<T>(props: Props<T>, reference: React.ForwardedRef<FlatList<T>>)` is indended to get rid of the error message:
`Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?`

### CODE REVIEW

**Comment by fivecar** [comment]
@dmytro-lytvyn : thank you so much for making this super-useful contribution. I'm in the middle of trying to get it merged right now, so I've added it to the Example app so that others can use it.

But here's what I'm currently getting with a horizontal list. Could you LMK if I'm potentially doing something wrong?

https://github.com/fivecar/react-native-draglist/assets/39933441/1f78f2bc-affd-4fe0-9e8e-cd9ee9036eda

Here's the code I added to example/src/App.tsx:
```typescript
      <DragList
        data={horzData}
        horizontal
        keyExtractor={keyExtractor}
        onReordered={onReorderedHorz}
        renderItem={renderItem}
      />
```

Did you run your change on iOS or Android? I wonder if the problem could be platform specific. I'll keep digging, but please LMK if there's something obvious that I'm missing.

**Comment by fivecar** [comment]
Ah, n/m. It all works now. Just needed to `npm install` the changes on my local repo prior to testing it again.

Ok - I'm going to try to make this generic as well. Change coming soon.

**Comment by fivecar** [comment]
Ok - I'm going to submit my updates/changes after merging this one, instead of putting it in the same PR, because I couldn't figure out how. 😄

**Comment by dmytro-lytvyn** [comment]
Oof I missed all the updates here - thanks for merging ! 🙏

**Pull request merged**
